

#ifndef ADC_CFG_H_
#define ADC_CFG_H_



#define ADC_VOLTAGE_REFRENCE		ADC_VREF_AVCC

#define ADC_ADJUST					ADC_RIGHT_ADJUST

#define ADC_CHANNEL					ADC_CHANNEL_1

#define ADC_CONVERTION_TRIGGER		ADC_AUTO_TRIGGER

#define ADC_PRESCALER				ADC_PRESC_128

#define ADC_INTERRUPT_STATE			ADC_INTERRUPT_DISABLE


#endif /* ADC_CFG_H_ */