#include "Ext_Int.h"

void setGlobalInterrupt(void){
	#if GLOBAL_INTERRUPT==GLOBAL_INTERRUPT_ENABLE
		
		SET_BIT(SREG,GLOBAL_INTERRUPT);
				
	#elif GLOBAL_INTERRUPT==GLOBAL_INTERRUPT_DISABLE
	
		CLR_BIT(SREG,GLOBAL_INTERRUPT);
	
	#endif
	};

void externalInterrupt0_Init(void){
		setGlobalInterrupt();
		
		SET_BIT(GICR,EXTERNAL_INTERRUPT0);
		
		#if EXTERNAL_INTERRUPT0_TRIGGER==INTERRUPT_TRIGGER_LOW_LEVEL
		
		CLR_BIT(MCUCSR,0);
		CLR_BIT(MCUCSR,1);
		
		#elif EXTERNAL_INTERRUPT0_TRIGGER==INTERRUPT_TRIGGER_RISING_EDGE
		
		SET_BIT(MCUCSR,0);
		SET_BIT(MCUCSR,1);
		
		#elif EXTERNAL_INTERRUPT0_TRIGGER==INTERRUPT_TRIGGER_FALLING_EDGE
		
		CLR_BIT(MCUCSR,0);
		SET_BIT(MCUCSR,1);
		
		#elif EXTERNAL_INTERRUPT0_TRIGGER==INTERRUPT_TRIGGER_ANY_LOGICAL_CHANGE
		
		SET_BIT(MCUCSR,0);
		CLR_BIT(MCUCSR,1);
		
		#endif
	};

void externalInterrupt1_Init(void){
	setGlobalInterrupt();
	SET_BIT(GICR,EXTERNAL_INTERRUPT1);
	
	#if EXTERNAL_INTERRUPT1_TRIGGER==INTERRUPT_TRIGGER_LOW_LEVEL
	
	CLR_BIT(MCUCSR,2);
	CLR_BIT(MCUCSR,3);
	
	#elif EXTERNAL_INTERRUPT1_TRIGGER==INTERRUPT_TRIGGER_RISING_EDGE
	
	SET_BIT(MCUCSR,2);
	SET_BIT(MCUCSR,3);
	
	#elif EXTERNAL_INTERRUPT1_TRIGGER==INTERRUPT_TRIGGER_FALLING_EDGE
	
	CLR_BIT(MCUCSR,2);
	SET_BIT(MCUCSR,3);
	
	#elif EXTERNAL_INTERRUPT1_TRIGGER==INTERRUPT_TRIGGER_ANY_LOGICAL_CHANGE
	
	SET_BIT(MCUCSR,2);
	CLR_BIT(MCUCSR,3);
	
	#endif
	
	};

void externalInterrupt2_Init(void){
	
	SET_BIT(GICR,EXTERNAL_INTERRUPT1);
	
	#if EXTERNAL_INTERRUPT1_TRIGGER==INTERRUPT_TRIGGER_RISING_EDGE
	
	SET_BIT(MCUCSR,6);

	
	#elif EXTERNAL_INTERRUPT1_TRIGGER==INTERRUPT_TRIGGER_FALLING_EDGE
	
	CLR_BIT(MCUCSR,6);
	
	#endif
	
	};
