

#ifndef _SEGMENT_CFG_H_
#define _SEGMENT_CFG_H_

#define SEGMENT_DATA_PORT		DIO_PORTA

#define SEGMENT_DATA_PIN1		DIO_PIN4
#define SEGMENT_DATA_PIN2		DIO_PIN5
#define SEGMENT_DATA_PIN3		DIO_PIN6
#define SEGMENT_DATA_PIN4		DIO_PIN7

#define SEGMENT_COM1_PORT		DIO_PORTB
#define SEGMENT_COM2_PORT		DIO_PORTB
#define SEGMENT_COM3_PORT		DIO_PORTB
#define SEGMENT_COM4_PORT		DIO_PORTB

#define SEGMENT_COM1_PIN		DIO_PIN3
#define SEGMENT_COM2_PIN		DIO_PIN5
#define SEGMENT_COM3_PIN		DIO_PIN6
#define SEGMENT_COM4_PIN		DIO_PIN7

#define SEGMENT_COM_ON		1
#define SEGMENT_COM_OFF		0

#define SEGMENT_COM1	0
#define SEGMENT_COM2	1
#define SEGMENT_COM3	2
#define SEGMENT_COM4	3

#endif /* 7_SEGMENT_CFG_H_ */