
#ifndef EXT_INT_CFG_H_
#define EXT_INT_CFG_H_

#define GLOBAL_INTERRUPT_MODE	GLOBAL_INTERRUPT_ENABLE

#define EXTERNAL_INTERRUPT0_TRIGGER			INTERRUPT_TRIGGER_RISING_EDGE

#define EXTERNAL_INTERRUPT1_TRIGGER			INTERRUPT_TRIGGER_RISING_EDGE

#define EXTERNAL_INTERRUPT2_TRIGGER			INTERRUPT_TRIGGER_RISING_EDGE


#endif /* EXT_INT_CFG_H_ */